### ISSUE TITLE
rename from Gittip to Gratipay

### ISSUE THREAD

**Issue by whit537** [KevinTCoughlin/node-gittip#1]
Per https://medium.com/gratipay-blog/gratitude-gratipay-ef24ad5e41f9. :-)

**Comment by techtonik** [comment]
Looks like it slipped away from radar. :turtle:

**Comment by KevinTCoughlin** [comment]
Feel free to fork. This is Github.

**Comment by techtonik** [comment]
I can run `s/gittip/gratipay/` over the sources, but I have no idea how to test javascript packages.

**Comment by KevinTCoughlin** [comment]
You could fork this repo and replace all the strings necessary & properly name / publish it. The primary issue is that once published on npm, a module cannot be renamed so that all dependents update automatically. The best that can be done is to put a deprecation warning in this module asking users to install the renamed one which I or someone else can add to this repo.

Also, I believe `make test` will run the tests for this repo.

**Comment by techtonik** [comment]
Forked and replaced in issue #1. What is the proper naming for publishing on npm?
